---
# nginx_proxy tasks

- name: Nginx Install
  apt:
    name: "nginx"
    state: present

- name: Nginx Custom Config
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
#  when: "'vm_1' in inventory_hostname" # Only for vm_1
  notify: "Nginx Reloader"
